<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Clear_Region</name>
   <tag></tag>
   <elementGuidId>f7251137-fe7e-4d56-b83a-71857b47987d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Region']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Region</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Region</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;js-page-content-wrapper&quot;]/main[@class=&quot;main-content&quot;]/div[1]/section[@class=&quot;container container--30-70&quot;]/div[@class=&quot;container__col container__col--30 container__col--left&quot;]/div[@class=&quot;container__inner&quot;]/div[@class=&quot;search__facets-wrapper is-left&quot;]/div[@class=&quot;search__facets-mount js-search-facets&quot;]/div[1]/div[@class=&quot;search-facets&quot;]/div[@class=&quot;search-facets__group is-open&quot;]/div[@class=&quot;search-facets__group-wrapper&quot;]/div[@class=&quot;search-facets__group-body&quot;]/div[@class=&quot;search-facets__group-selected&quot;]/ul[@class=&quot;search-facets__group-values&quot;]/li[1]/input[@id=&quot;Region&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Region']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
   </webElementXpaths>
</WebElementEntity>
