<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>use (1)</name>
   <tag></tag>
   <elementGuidId>19671735-e03c-444d-98ef-a8ac250cf11d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>use</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xlink:href</name>
      <type>Main</type>
      <value>/assets/demo-build/img/svg-sprite.svg#chevron-down</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;js-page-content-wrapper&quot;]/main[@class=&quot;main-content&quot;]/div[1]/section[@class=&quot;container container--30-70&quot;]/div[@class=&quot;container__col container__col--30 container__col--left&quot;]/div[@class=&quot;container__inner&quot;]/div[@class=&quot;search__facets-wrapper is-left&quot;]/div[@class=&quot;search__facets-mount js-search-facets&quot;]/div[1]/div[@class=&quot;search-facets&quot;]/div[@class=&quot;search-facets__group&quot;]/div[@class=&quot;search-facets__group-heading&quot;]/button[@class=&quot;search-facets__group-toggle&quot;]/svg[@class=&quot;icon&quot;]/use[1]</value>
   </webElementProperties>
</WebElementEntity>
